### ISSUE TITLE
Users with no channel defined can crash the server

### ISSUE THREAD

**Issue by nugget** [nugget/roon-community-dj#27]
Users with empty/bogus channel names can crash the server.

```
/usr/home/djserver/roon-community-dj/server.js:153
    cUC = msg.channel.toUpperCase();
                      ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at didTheDJDrop (/usr/home/djserver/roon-community-dj/server.js:153:23)
    at WebSocket.close (/usr/home/djserver/roon-community-dj/server.js:133:9)
    at WebSocket.emit (events.js:328:22)
    at WebSocket.emitClose (/usr/home/djserver/roon-community-dj/node_modules/ws/lib/websocket.js:194:10)
    at Socket.socketOnClose (/usr/home/djserver/roon-community-dj/node_modules/ws/lib/websocket.js:862:15)
```

**Comment by nugget** [comment]
Resolved with #26
